-- Chức năng đăng ký
use QuanLyBanHang
go

-- Chức năng đăng ký tài khoản
CREATE OR ALTER PROCEDURE REGISTER
	@ID NVARCHAR(50),
	@PASS NVARCHAR(50),
	@NAME NVARCHAR(50),
	@DOB DATE,
	@ADDR NVARCHAR(50),
	@PHONE NVARCHAR(20),
	@EMAIL NVARCHAR(50),
	@FLAG int out
AS
BEGIN
	IF EXISTS(SELECT 1 FROM KHACH_HANG WHERE MA_KH = @ID)
		BEGIN
			SET @FLAG = 0
			RETURN
		END
	DECLARE @MA_GIO_HANG NVARCHAR (50)
	SET @MA_GIO_HANG = @ID + '_gh'
	INSERT INTO GIO_HANG VALUES (@MA_GIO_HANG, null, 0)

	
	INSERT INTO KHACH_HANG VALUES (@ID, @MA_GIO_HANG, null, @NAME, @DOB, @ADDR, @PHONE, @EMAIL)
	UPDATE GIO_HANG SET MA_KH = @ID where MA_GIO_HANG = @MA_GIO_HANG
	INSERT INTO TAI_KHOAN VALUES (@ID, @PASS)
	SET @FLAG = 1
END
GO

-- Chức năng đăng nhập
CREATE OR ALTER PROCEDURE LOG_IN  @ID NVARCHAR(50),
                         @PASS AS CHAR(50),
                         @FLAG AS INT OUT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM TAI_KHOAN AS TK WHERE TK.MA_KH = @ID AND TK.MAT_KHAU = @PASS)
    BEGIN
        SET @FLAG = 1
		RETURN
    END

	ELSE
	BEGIN
		SET @FLAG = 0
	END
END
GO

-- Chức năng tìm kiếm theo tên
CREATE OR ALTER PROCEDURE SEARCH
	@NAME NVARCHAR(50),
	@CATEGORY NVARCHAR(50)
AS
BEGIN
	IF(@CATEGORY = '')
	BEGIN
		SELECT SP.TEN_SP, SP.TEN_DM, SP.GIA_SP, SP.SO_LUONG_CON_LAI, SP.MO_TA, SP.MA_CUA_HANG, SP.MA_SP
		FROM SAN_PHAM AS SP 
		WHERE SP.TEN_SP LIKE '%'+@NAME+'%'
	END

	ELSE
	BEGIN
		SELECT SP.TEN_SP, SP.GIA_SP, SP.SO_LUONG_CON_LAI, SP.MO_TA, SP.MA_CUA_HANG, SP.MA_SP
		FROM SAN_PHAM AS SP 
		WHERE SP.TEN_SP LIKE '%'+@NAME+'%' AND SP.TEN_DM = @CATEGORY
	END
END
GO

-- Chức năng thêm vào giỏ hàng
CREATE OR ALTER PROCEDURE ADD_TO_CART
	@MA_GIO_HANG NVARCHAR(50),
	@MA_SAN_PHAM NVARCHAR(50),
	@SO_LUONG INT
AS
BEGIN
	DECLARE @FULL_PRICE MONEY,
			@PRICE MONEY,
			@TOTAL MONEY,
			@NAME NVARCHAR(50)
	SET @FULL_PRICE = 0
	SET @PRICE = 0
    SET @TOTAL = 0
    SELECT @PRICE = SP.GIA_SP  FROM SAN_PHAM AS SP WHERE SP.MA_SP = @MA_SAN_PHAM
	SELECT @NAME = SP.TEN_SP  FROM SAN_PHAM AS SP WHERE SP.MA_SP = @MA_SAN_PHAM
	
    INSERT INTO CHI_TIET_GIO_HANG(MA_GIO_HANG, MA_SP, SO_LUONG, TEN_SP, GIA) VALUES (@MA_GIO_HANG, @MA_SAN_PHAM, @SO_LUONG, @NAME, @PRICE)

	--Kiểm tra xem đã insert thành công hay chưa, nếu rồi thì cập nhật số tiền có trong giỏ hàng
    IF(@@rowcount = 1) 
    BEGIN
        SET @FULL_PRICE = @PRICE * @SO_LUONG
        SELECT @TOTAL = GH.TONG_TIEN FROM GIO_HANG AS GH WHERE GH.MA_GIO_HANG = @MA_GIO_HANG
        SET @TOTAL += @FULL_PRICE
        UPDATE GIO_HANG SET TONG_TIEN = @TOTAL WHERE MA_GIO_HANG = @MA_GIO_HANG
    END
END
GO

--Chức năng chỉnh sửa số lượng sản phẩm
CREATE OR ALTER PROCEDURE CHANGE_QUANTITY
	@MA_GH NVARCHAR(50),
	@MA_SP NVARCHAR(50),
	@SO_LUONG_MOI INT
AS
BEGIN

	DECLARE @SO_LUONG_CU INT,
			@GIA MONEY
	SELECT @GIA = SP.GIA_SP FROM SAN_PHAM SP WHERE SP.MA_SP = @MA_SP

	SELECT @SO_LUONG_CU = CTGH.SO_LUONG 
	FROM CHI_TIET_GIO_HANG CTGH 
	WHERE CTGH.MA_GIO_HANG = @MA_GH AND CTGH.MA_SP = @MA_SP

	IF(@SO_LUONG_MOI < @SO_LUONG_CU)
	BEGIN
		UPDATE GIO_HANG SET TONG_TIEN -= @GIA*(@SO_LUONG_CU - @SO_LUONG_MOI) 
						WHERE MA_GIO_HANG = @MA_GH
	END

	IF(@SO_LUONG_MOI > @SO_LUONG_CU)
	BEGIN
		UPDATE GIO_HANG SET TONG_TIEN += @GIA*(@SO_LUONG_MOI - @SO_LUONG_CU) 
						WHERE MA_GIO_HANG = @MA_GH
	END

	UPDATE CHI_TIET_GIO_HANG SET SO_LUONG = @SO_LUONG_MOI 
							WHERE MA_GIO_HANG = @MA_GH AND MA_SP = @MA_SP
END
GO

--Chức năng xóa sản phẩm khỏi giỏ hàng
CREATE OR ALTER PROCEDURE DELETE_PRODUCT
    @MA_GH NVARCHAR(50),
    @MA_SP NVARCHAR(50)
AS
BEGIN
    DECLARE @GIA MONEY,
			@SO_LUONG INT
    SET @SO_LUONG = 0

    SELECT @GIA = GH.GIA, @SO_LUONG= GH.SO_LUONG 
	FROM CHI_TIET_GIO_HANG AS GH 
	WHERE GH.MA_GIO_HANG = @MA_GH AND GH.MA_SP = @MA_SP

    UPDATE GIO_HANG SET TONG_TIEN -= @GIA * @SO_LUONG 
					WHERE MA_GIO_HANG= @MA_GH

    DELETE FROM CHI_TIET_GIO_HANG WHERE MA_SP = @MA_SP
END
GO

--Chức năng xem sản phẩm hiện có trong giỏ hàng
CREATE OR ALTER PROCEDURE SHOW_CART_PRODUCT
	@MA_GH NVARCHAR(50)
AS
BEGIN
    SELECT CTGH.TEN_SP, CTGH.SO_LUONG, CTGH.GIA, CTGH.MA_SP
	FROM CHI_TIET_GIO_HANG CTGH 
	WHERE CTGH.MA_GIO_HANG = @MA_GH
END
GO

---- Chức năng chuyển đơn mua hàng từ khách hàng sang chủ cửa hàng
--SỬ DỤNG CURSOR
CREATE OR ALTER PROCEDURE BILL_REQUEST
    @MA_GIO_HANG NVARCHAR(50),
    @MA_KH NVARCHAR(50)
AS
BEGIN TRAN
    DECLARE @MA_SP NVARCHAR(50), 
			@SL_SAN_PHAM INT,
			@MA_GH NVARCHAR(50),
			@TEN_SP NVARCHAR(50),
			@DON_GIA MONEY,
			@MA_CH NVARCHAR(50),
			@DIA_CHI NVARCHAR(50)
	SELECT @DIA_CHI = KH.DIA_CHI FROM KHACH_HANG KH WHERE KH.MA_KH = @MA_KH

    DECLARE cusorSales_request CURSOR LOCAL FOR
    SELECT @MA_GH, MA_SP, SO_LUONG, TEN_SP, GIA FROM CHI_TIET_GIO_HANG
    OPEN cusorSales_request
    FETCH NEXT FROM cusorSales_request INTO @MA_CH, @MA_SP, @SL_SAN_PHAM, @TEN_SP, @DON_GIA
    SELECT @MA_GH = GHCT.MA_GIO_HANG FROM CHI_TIET_GIO_HANG GHCT WHERE GHCT.MA_SP = @MA_SP
    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF(@MA_GH = @MA_GIO_HANG)
        BEGIN
            SELECT @MA_CH = SP.MA_CUA_HANG FROM SAN_PHAM AS SP WHERE SP.MA_SP = @MA_SP

			DECLARE @MA_DON_HANG_TEMP INT
            IF NOT EXISTS(SELECT 1 FROM DANH_SACH_DON_HANG DSDH WHERE DSDH.MA_CUA_HANG = @MA_CH and DSDH.NGAY_MUA = CAST(CAST(GETDATE() AS DATE) AS DATE))
            BEGIN
                INSERT INTO DANH_SACH_DON_HANG VALUES (@MA_KH, @MA_CH, @DIA_CHI, CAST(CAST(GETDATE() AS DATE) AS DATE), N'Chưa nhận')
				SELECT @MA_DON_HANG_TEMP = DS.MA_DON_HANG FROM DANH_SACH_DON_HANG DS WHERE DS.MA_CUA_HANG = @MA_CH
                INSERT INTO CHI_TIET_DON_HANG VALUES (@MA_DON_HANG_TEMP, @MA_SP, @SL_SAN_PHAM, @TEN_SP ,@DON_GIA, CAST(CAST(GETDATE() AS DATE) AS DATE))
			END

			ELSE
			BEGIN
				SELECT @MA_DON_HANG_TEMP = DS.MA_DON_HANG FROM DANH_SACH_DON_HANG DS WHERE DS.MA_CUA_HANG = @MA_CH
				IF EXISTS(SELECT 1 FROM CHI_TIET_DON_HANG CT WHERE CT.MA_DON_HANG = @MA_DON_HANG_TEMP AND CT.MA_SP = @MA_SP)
				BEGIN
					DECLARE @SL INT
					SELECT @SL = CT.SO_LUONG
					FROM CHI_TIET_DON_HANG CT
					WHERE CT.MA_DON_HANG = @MA_DON_HANG_TEMP AND CT.MA_SP = @MA_SP
					SET @SL = @SL + @SL_SAN_PHAM
					UPDATE CHI_TIET_DON_HANG SET SO_LUONG = @SL 
					WHERE MA_DON_HANG = @MA_DON_HANG_TEMP AND MA_SP = @MA_SP
				END
				ELSE
				BEGIN
					INSERT INTO CHI_TIET_DON_HANG VALUES (@MA_DON_HANG_TEMP, @MA_SP, @SL_SAN_PHAM, @TEN_SP ,@DON_GIA, CAST(GETDATE() AS DATE))
				END
			END
        END
        FETCH NEXT FROM cusorSales_request INTO @MA_GH, @MA_SP, @SL_SAN_PHAM, @TEN_SP, @DON_GIA
        SELECT @MA_GH = CTGH.MA_GIO_HANG FROM CHI_TIET_GIO_HANG CTGH WHERE CTGH.MA_SP = @MA_SP
    END
        CLOSE cusorSales_request
        DEALLOCATE cusorSales_request
COMMIT TRAN
GO

-- Chức năng kiểm tra shop đã có hay chưa
CREATE OR ALTER PROCEDURE CHECK_SHOP
    @MA_KH NVARCHAR(50),
    @FLAG INT OUT
AS
BEGIN
    SET @FLAG =0
    IF EXISTS(SELECT 1 FROM KHACH_HANG AS KH WHERE KH.MA_KH = @MA_KH AND KH.MA_CUA_HANG IS NOT NULL)
    BEGIN
        SET @FLAG = 1
    END
END
GO

-- Chức năng đăng ký bán hàng
CREATE OR ALTER PROCEDURE SHOP_REGISTER
    @MA_KH NVARCHAR(50)
AS
BEGIN
    DECLARE @MA_CH NVARCHAR(50),
			@SDT NVARCHAR(20),
			@EMAIL NVARCHAR(20)
    SET @MA_CH = @MA_KH + '_ch'
	SELECT @SDT = SDT FROM KHACH_HANG WHERE MA_KH = @MA_KH
	SELECT @EMAIL = EMAIL FROM KHACH_HANG WHERE MA_KH = @MA_KH

    INSERT INTO CUA_HANG VALUES (@MA_CH, @MA_KH, @SDT, @EMAIL)
    IF(@@ROWCOUNT = 1)
	BEGIN
		UPDATE KHACH_HANG SET MA_CUA_HANG = @MA_CH WHERE MA_KH = @MA_KH
    END
END
GO

-- Chức năng xuất các sản phẩm hiện có tại giỏ hàng
CREATE OR ALTER PROCEDURE SHOW_SHOP_PRODUCT
    @MA_CH NVARCHAR(50)
AS
BEGIN
    SELECT SP.MA_SP, SP.TEN_SP, SP.TEN_DM, SP.GIA_SP,  SP.SO_LUONG_CON_LAI, SP.MO_TA 
	FROM SAN_PHAM SP 
	WHERE SP.MA_CUA_HANG = @MA_CH
END
GO

-- Chức năng thêm sản phẩm vào cửa hàng
CREATE OR ALTER PROCEDURE ADD_PRODUCT
    @MA_CH NVARCHAR(50),
    @TEN_SP NVARCHAR(50),
	@TEN_DM NVARCHAR(50),
    @GIA_SP MONEY,
    @SL_CON_LAI INT,
    @MO_TA NVARCHAR(2000)
AS
BEGIN
    INSERT INTO SAN_PHAM VALUES (@MA_CH, @TEN_DM, @TEN_SP, @GIA_SP, @SL_CON_LAI, @MO_TA)
END
GO

-- Chức năng xóa sản phẩm ở cửa hàng
CREATE OR ALTER PROCEDURE DELETE_SHOP_PRODUCT
@MA_SP NVARCHAR(50)
AS
BEGIN
    DELETE FROM SAN_PHAM WHERE MA_SP = @MA_SP
END
GO

-- Chức năng xóa hết sản phẩm trong giỏ hàng
CREATE OR ALTER PROCEDURE DELETE_ALL_PRODUCT
    @MA_GH NVARCHAR(50)
AS
BEGIN
    UPDATE GIO_HANG SET TONG_TIEN = 0 WHERE MA_GIO_HANG = @MA_GH
    DELETE FROM CHI_TIET_GIO_HANG WHERE MA_GIO_HANG = @MA_GH
END
GO

-- Chức năng xác nhận đơn hàng
CREATE OR ALTER PROCEDURE RECEIVE_CONFIRM 
    @MA_DH int
AS
BEGIN
	UPDATE DANH_SACH_DON_HANG SET TRANG_THAI = N'Đã nhận' WHERE MA_DON_HANG = @MA_DH
END
GO
